name: CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Build Docker image
        run: docker build -t my-app ./stage-04-docker/docker

      - name: Run container
        run: docker run -d -p 8080:80 --name my-app-container my-app

      - name: Healthcheck
        run: bash stage-06-ci/scripts/healthcheck-ci.sh

