name: CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Make script executable
        run: chmod +x stage-03-shell-git/scripts/sysinfo.sh

      - name: Run sysinfo script
        run: bash stage-03-shell-git/scripts/sysinfo.sh


